In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col = 0)

In [3]:
matches.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,Match Report,NaN,13.0,1.0,17.8,0.0,0,0,2024,Liverpool
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,Match Report,NaN,25.0,9.0,16.8,1.0,0,1,2024,Liverpool
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,Match Report,NaN,9.0,4.0,17.2,1.0,0,0,2024,Liverpool
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,Match Report,NaN,17.0,4.0,14.7,0.0,0,0,2024,Liverpool
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,Match Report,NaN,16.0,5.0,15.8,0.0,0,0,2024,Liverpool

In [4]:
matches.shape

(1366, 27)

In [5]:
matches['Team'].value_counts()

Nottingham Forest           69
Aston Villa                 69
Brentford                   69
West Ham United             69
Fulham                      69
Liverpool                   68
Wolverhampton Wanderers     68
Everton                     68
Crystal Palace              68
Arsenal                     68
Bournemouth                 68
Brighton and Hove Albion    68
Newcastle United            68
Manchester United           68
Tottenham Hotspur           68
Manchester City             68
Chelsea                     67
Leicester City              38
Leeds United                38
Southampton                 38
Luton Town                  31
Burnley                     31
Sheffield United            30
Name: Team, dtype: int64

In [6]:
matches.dtypes

Date             object
Time             object
Comp             object
Round            object
Day              object
Venue            object
Result           object
GF              float64
GA              float64
Opponent         object
xG              float64
xGA             float64
Poss            float64
Attendance      float64
Captain          object
Formation        object
Referee          object
Match Report     object
Notes           float64
Sh              float64
SoT             float64
Dist            float64
FK              float64
PK                int64
PKatt             int64
Season            int64
Team             object
dtype: object

In [7]:
matches['Date'] = pd.to_datetime(matches['Date'])

In [8]:
matches['venue_code'] = matches['Venue'].astype('category')

In [9]:
matches['venue_code'] = matches['venue_code'].cat.codes

In [10]:
matches['opp_code'] = matches['Opponent'].astype('category').cat.codes

In [11]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Sh,SoT,Dist,FK,PK,PKatt,Season,Team,venue_code,opp_code
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,13.0,1.0,17.8,0.0,0,0,2024,Liverpool,0,6
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,25.0,9.0,16.8,1.0,0,1,2024,Liverpool,1,2
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,9.0,4.0,17.2,1.0,0,0,2024,Liverpool,0,16
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,17.0,4.0,14.7,0.0,0,0,2024,Liverpool,1,1
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,16.0,5.0,15.8,0.0,0,0,2024,Liverpool,0,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1.0,3.0,Newcastle Utd,...,4.0,3.0,17.3,0.0,0,0,2023,Southampton,0,16
43,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3.0,4.0,Nott'ham Forest,...,18.0,4.0,14.0,0.0,1,1,2023,Southampton,0,17
44,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0.0,2.0,Fulham,...,5.0,1.0,24.2,0.0,0,0,2023,Southampton,1,9
45,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1.0,3.0,Brighton,...,5.0,1.0,13.8,1.0,0,0,2023,Southampton,0,4
46,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4.0,4.0,Liverpool,...,15.0,10.0,17.5,1.0,0,0,2023,Southampton,1,12

In [12]:
matches['hour'] = matches['Time'].str.replace(":.+", "", regex = True).astype('int')
#":.+" the .+ tells the the system to replace one or more chracters after the :
#":." will only replace the first element after :

In [13]:
matches.dtypes

Date            datetime64[ns]
Time                    object
Comp                    object
Round                   object
Day                     object
Venue                   object
Result                  object
GF                     float64
GA                     float64
Opponent                object
xG                     float64
xGA                    float64
Poss                   float64
Attendance             float64
Captain                 object
Formation               object
Referee                 object
Match Report            object
Notes                  float64
Sh                     float64
SoT                    float64
Dist                   float64
FK                     float64
PK                       int64
PKatt                    int64
Season                   int64
Team                    object
venue_code                int8
opp_code                  int8
hour                     int32
dtype: object

In [14]:
matches['day_code'] = matches['Date'].dt

In [15]:
matches.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,Season,Team,venue_code,opp_code,hour,day_code
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,17.8,0.0,0,0,2024,Liverpool,0,6,16,<pandas.core.indexes.accessors.DatetimePropert...
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,16.8,1.0,0,1,2024,Liverpool,1,2,15,<pandas.core.indexes.accessors.DatetimePropert...
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,17.2,1.0,0,0,2024,Liverpool,0,16,16,<pandas.core.indexes.accessors.DatetimePropert...
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,14.7,0.0,0,0,2024,Liverpool,1,1,14,<pandas.core.indexes.accessors.DatetimePropert...
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,15.8,0.0,0,0,2024,Liverpool,0,22,12,<pandas.core.indexes.accessors.DatetimePropert...

In [16]:
matches['day_code'] = matches['Date'].dt.dayofweek

In [17]:
matches.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,Season,Team,venue_code,opp_code,hour,day_code
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,17.8,0.0,0,0,2024,Liverpool,0,6,16,6
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,16.8,1.0,0,1,2024,Liverpool,1,2,15,5
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,17.2,1.0,0,0,2024,Liverpool,0,16,16,6
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,14.7,0.0,0,0,2024,Liverpool,1,1,14,6
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,15.8,0.0,0,0,2024,Liverpool,0,22,12,5

In [18]:
matches['target'] = (matches['Result'] == "W").astype('int')

In [19]:
matches

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,venue_code,opp_code,hour,day_code,target
0,2023-08-13,16:30,Premier League,Matchweek 1,Sun,Away,D,1.0,1.0,Chelsea,...,0.0,0,0,2024,Liverpool,0,6,16,6,0
1,2023-08-19,15:00,Premier League,Matchweek 2,Sat,Home,W,3.0,1.0,Bournemouth,...,1.0,0,1,2024,Liverpool,1,2,15,5,1
2,2023-08-27,16:30,Premier League,Matchweek 3,Sun,Away,W,2.0,1.0,Newcastle Utd,...,1.0,0,0,2024,Liverpool,0,16,16,6,1
3,2023-09-03,14:00,Premier League,Matchweek 4,Sun,Home,W,3.0,0.0,Aston Villa,...,0.0,0,0,2024,Liverpool,1,1,14,6,1
4,2023-09-16,12:30,Premier League,Matchweek 5,Sat,Away,W,3.0,1.0,Wolves,...,0.0,0,0,2024,Liverpool,0,22,12,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Away,L,1.0,3.0,Newcastle Utd,...,0.0,0,0,2023,Southampton,0,16,14,6,0
43,2023-05-08,20:00,Premier League,Matchweek 35,Mon,Away,L,3.0,4.0,Nott'ham Forest,...,0.0,1,1,2023,Southampton,0,17,20,0,0
44,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,L,0.0,2.0,Fulham,...,0.0,0,0,2023,Southampton,1,9,15,5,0
45,2023-05-21,14:00,Premier League,Matchweek 37,Sun,Away,L,1.0,3.0,Brighton,...,1.0,0,0,2023,Southampton,0,4,14,6,0
46,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,D,4.0,4.0,Liverpool,...,1.0,0,0,2023,Southampton,1,12,16,6,0

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier(n_estimators = 50, min_samples_split = 10, random_state = 1)

In [22]:
train = matches[matches["Date"] < '2024-01-01']

In [23]:
test = matches[matches['Date'] > '2024-01-01']

In [24]:
predictors = ['venue_code', 'opp_code', 'hour', 'day_code']

In [25]:
rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [26]:
preds = rf.predict(test[predictors])

In [27]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score

In [28]:
accuracy = accuracy_score(test['target'], preds)

In [29]:
accuracy

0.6226415094339622

In [30]:
combined = pd.DataFrame({'Actual' : test["target"], 'Predicted' : preds})

In [31]:
combined

    Actual  Predicted
31       1          0
34       1          1
35       0          0
36       1          1
37       1          0
..     ...        ...
28       0          0
29       0          0
30       0          0
31       0          0
32       0          0

[212 rows x 2 columns]

In [32]:
pd.crosstab(index=combined["Actual"], columns=combined["Predicted"])
#Index is the rows

Predicted    0   1
Actual
0          100  38
1           42  32

In [33]:
precision_score(test['target'], preds) #This will tell us when we predicted a win what % of the time was it an actual win.

0.45714285714285713

In [34]:
team_matches = matches.groupby("Team")

In [35]:
group = team_matches.get_group("Manchester United")

In [36]:
group

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,FK,PK,PKatt,Season,Team,venue_code,opp_code,hour,day_code,target
0,2023-08-14,20:00,Premier League,Matchweek 1,Mon,Home,W,1.0,0.0,Wolves,...,0.0,0,0,2024,Manchester United,1,22,20,0,1
1,2023-08-19,17:30,Premier League,Matchweek 2,Sat,Away,L,0.0,2.0,Tottenham,...,1.0,0,0,2024,Manchester United,0,20,17,5,0
2,2023-08-26,15:00,Premier League,Matchweek 3,Sat,Home,W,3.0,2.0,Nott'ham Forest,...,0.0,1,1,2024,Manchester United,1,17,15,5,1
3,2023-09-03,16:30,Premier League,Matchweek 4,Sun,Away,L,1.0,3.0,Arsenal,...,0.0,0,0,2024,Manchester United,0,0,16,6,0
4,2023-09-16,15:00,Premier League,Matchweek 5,Sat,Home,L,1.0,3.0,Brighton,...,1.0,0,0,2024,Manchester United,1,4,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2023-05-07,19:00,Premier League,Matchweek 35,Sun,Away,L,0.0,1.0,West Ham,...,0.0,0,0,2023,Manchester United,0,21,19,6,0
57,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,W,2.0,0.0,Wolves,...,2.0,0,0,2023,Manchester United,1,22,15,5,1
58,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Away,W,1.0,0.0,Bournemouth,...,0.0,0,0,2023,Manchester United,0,2,15,5,1
59,2023-05-25,20:00,Premier League,Matchweek 32,Thu,Home,W,4.0,1.0,Chelsea,...,0.0,1,1,2023,Manchester United,1,6,20,3,1
60,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Home,W,2.0,1.0,Fulham,...,1.0,0,0,2023,Manchester United,1,9,16,6,1

In [37]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("Date") #To ensure that the dates are in ascending order.
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    #group = group.dropna(subset=new_cols)
    return group

In [38]:
group.columns

Index(['Date', 'Time', 'Comp', 'Round', 'Day', 'Venue', 'Result', 'GF', 'GA',
       'Opponent', 'xG', 'xGA', 'Poss', 'Attendance', 'Captain', 'Formation',
       'Referee', 'Match Report', 'Notes', 'Sh', 'SoT', 'Dist', 'FK', 'PK',
       'PKatt', 'Season', 'Team', 'venue_code', 'opp_code', 'hour', 'day_code',
       'target'],
      dtype='object')

In [39]:
cols = ['GF', 'GA', 'xG', 'xGA', 'Sh', 'SoT', 'Poss']

In [40]:
new_cols = []
for i in cols:
    new_cols.append(i + "_rolling")

In [41]:
new_cols

['GF_rolling',
 'GA_rolling',
 'xG_rolling',
 'xGA_rolling',
 'Sh_rolling',
 'SoT_rolling',
 'Poss_rolling']

In [42]:
rolling_averages(group, cols, new_cols)

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,hour,day_code,target,GF_rolling,GA_rolling,xG_rolling,xGA_rolling,Sh_rolling,SoT_rolling,Poss_rolling
0,2022-08-07,14:00,Premier League,Matchweek 1,Sun,Home,L,1.0,2.0,Brighton,...,14,6,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-08-13,17:30,Premier League,Matchweek 2,Sat,Away,L,0.0,4.0,Brentford,...,17,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-08-22,20:00,Premier League,Matchweek 3,Mon,Home,W,2.0,1.0,Liverpool,...,20,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-08-27,12:30,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Southampton,...,12,5,1,1.000000,2.333333,1.366667,1.466667,15.000000,4.666667,52.666667
4,2022-09-01,20:00,Premier League,Matchweek 5,Thu,Away,W,1.0,0.0,Leicester City,...,20,3,1,1.000000,1.666667,1.266667,1.433333,13.000000,4.333333,49.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,2024-02-24,15:00,Premier League,Matchweek 26,Sat,Home,L,1.0,2.0,Fulham,...,15,5,0,2.333333,0.666667,1.800000,1.866667,16.666667,6.000000,45.666667
37,2024-03-03,15:30,Premier League,Matchweek 27,Sun,Away,L,1.0,3.0,Manchester City,...,15,6,0,1.666667,1.333333,2.133333,1.800000,19.666667,7.000000,47.666667
38,2024-03-09,12:30,Premier League,Matchweek 28,Sat,Home,W,2.0,0.0,Everton,...,12,5,1,1.333333,2.000000,1.600000,2.100000,15.000000,5.666667,42.000000
40,2024-03-30,20:00,Premier League,Matchweek 30,Sat,Away,D,1.0,1.0,Brentford,...,20,5,0,1.333333,1.666667,1.533333,2.033333,12.333333,5.000000,45.000000
41,2024-04-04,20:15,Premier League,Matchweek 31,Thu,Away,L,3.0,4.0,Chelsea,...,20,3,0,1.333333,1.333333,1.166667,2.700000,9.000000,4.000000,43.666667

In [43]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("Date") #To ensure that the dates are in ascending order.
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [44]:
rolling_averages(group, cols, new_cols)

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,hour,day_code,target,GF_rolling,GA_rolling,xG_rolling,xGA_rolling,Sh_rolling,SoT_rolling,Poss_rolling
3,2022-08-27,12:30,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Southampton,...,12,5,1,1.000000,2.333333,1.366667,1.466667,15.000000,4.666667,52.666667
4,2022-09-01,20:00,Premier League,Matchweek 5,Thu,Away,W,1.0,0.0,Leicester City,...,20,3,1,1.000000,1.666667,1.266667,1.433333,13.000000,4.333333,49.000000
5,2022-09-04,16:30,Premier League,Matchweek 6,Sun,Home,W,3.0,1.0,Arsenal,...,16,6,1,1.333333,0.333333,1.466667,1.133333,11.000000,3.666667,42.666667
8,2022-10-02,14:00,Premier League,Matchweek 9,Sun,Away,L,3.0,6.0,Manchester City,...,14,6,0,1.666667,0.333333,1.366667,1.133333,10.000000,4.000000,46.000000
10,2022-10-09,19:00,Premier League,Matchweek 10,Sun,Away,W,2.0,1.0,Everton,...,19,6,1,2.333333,2.333333,1.566667,1.733333,10.000000,5.000000,44.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,2024-02-24,15:00,Premier League,Matchweek 26,Sat,Home,L,1.0,2.0,Fulham,...,15,5,0,2.333333,0.666667,1.800000,1.866667,16.666667,6.000000,45.666667
37,2024-03-03,15:30,Premier League,Matchweek 27,Sun,Away,L,1.0,3.0,Manchester City,...,15,6,0,1.666667,1.333333,2.133333,1.800000,19.666667,7.000000,47.666667
38,2024-03-09,12:30,Premier League,Matchweek 28,Sat,Home,W,2.0,0.0,Everton,...,12,5,1,1.333333,2.000000,1.600000,2.100000,15.000000,5.666667,42.000000
40,2024-03-30,20:00,Premier League,Matchweek 30,Sat,Away,D,1.0,1.0,Brentford,...,20,5,0,1.333333,1.666667,1.533333,2.033333,12.333333,5.000000,45.000000
41,2024-04-04,20:15,Premier League,Matchweek 31,Thu,Away,L,3.0,4.0,Chelsea,...,20,3,0,1.333333,1.333333,1.166667,2.700000,9.000000,4.000000,43.666667

In [45]:
matches_rolling = matches.groupby("Team").apply(lambda x : rolling_averages(x, cols, new_cols))

In [46]:
matches_rolling

                                 Date   Time            Comp         Round  \
Team
Arsenal                 3  2022-08-27  17:30  Premier League   Matchweek 4
                        4  2022-08-31  19:30  Premier League   Matchweek 5
                        5  2022-09-04  16:30  Premier League   Matchweek 6
                        7  2022-09-18  12:00  Premier League   Matchweek 8
                        8  2022-10-01  12:30  Premier League   Matchweek 9
...                               ...    ...             ...           ...
Wolverhampton Wanderers 30 2024-02-25  13:30  Premier League  Matchweek 26
                        32 2024-03-02  15:00  Premier League  Matchweek 27
                        33 2024-03-09  15:00  Premier League  Matchweek 28
                        35 2024-03-30  17:30  Premier League  Matchweek 30
                        36 2024-04-02  19:45  Premier League  Matchweek 31

                            Day Venue Result   GF   GA        Opponent  ...  \
Team                                                                    ...
Arsenal                 3   Sat  Home      W  2.0  1.0          Fulham  ...
                        4   Wed  Home      W  2.0  1.0     Aston Villa  ...
                        5   Sun  Away      L  1.0  3.0  Manchester Utd  ...
                        7   Sun  Away      W  3.0  0.0       Brentford  ...
                        8   Sat  Home      W  3.0  1.0       Tottenham  ...
...                         ...   ...    ...  ...  ...             ...  ...
Wolverhampton Wanderers 30  Sun  Home      W  1.0  0.0   Sheffield Utd  ...
                        32  Sat  Away      L  0.0  3.0   Newcastle Utd  ...
                        33  Sat  Home      W  2.0  1.0          Fulham  ...
                        35  Sat  Away      L  0.0  2.0     Aston Villa  ...
                        36  Tue  Away      D  1.0  1.0         Burnley  ...

                            hour  day_code  target  GF_rolling GA_rolling  \
Team
Arsenal                 3     17         5       1    3.000000   0.666667
                        4     19         2       1    3.000000   1.000000
                        5     16         6       0    2.333333   0.666667
                        7     12         6       1    1.666667   1.666667
                        8     12         5       1    2.000000   1.333333
...                          ...       ...     ...         ...        ...
Wolverhampton Wanderers 30    13         6       1    2.000000   1.666667
                        32    15         5       0    1.000000   1.000000
                        33    15         5       1    1.000000   1.333333
                        35    17         5       0    1.000000   1.333333
                        36    19         1       0    0.666667   2.000000

                           xG_rolling xGA_rolling Sh_rolling  SoT_rolling  \
Team
Arsenal                 3    1.666667    0.666667  14.333333     5.000000
                        4    2.200000    0.533333  18.333333     7.000000
                        5    2.100000    0.500000  19.333333     7.333333
                        7    2.100000    0.900000  20.000000     6.333333
                        8    1.733333    0.800000  17.000000     6.000000
...                               ...         ...        ...          ...
Wolverhampton Wanderers 30   1.600000    1.733333  14.000000     6.000000
                        32   1.366667    1.366667  14.000000     4.666667
                        33   1.300000    1.433333  12.333333     4.000000
                        35   0.966667    1.766667  11.000000     2.666667
                        36   1.033333    1.900000  11.000000     3.000000

                            Poss_rolling
Team
Arsenal                 3      50.333333
                        4      59.333333
                        5      62.333333
                        7      63.333333
                        8      60.666667
...                                  ...
Wolverhampton Wanderers 30     45.333333
                        32     54.333333
                        33     49.333333
                        35     55.666667
                        36     52.000000

[1297 rows x 39 columns]

In [47]:
matches_rolling = matches_rolling.droplevel('Team')

In [48]:
matches_rolling

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,hour,day_code,target,GF_rolling,GA_rolling,xG_rolling,xGA_rolling,Sh_rolling,SoT_rolling,Poss_rolling
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,17,5,1,3.000000,0.666667,1.666667,0.666667,14.333333,5.000000,50.333333
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,19,2,1,3.000000,1.000000,2.200000,0.533333,18.333333,7.000000,59.333333
5,2022-09-04,16:30,Premier League,Matchweek 6,Sun,Away,L,1.0,3.0,Manchester Utd,...,16,6,0,2.333333,0.666667,2.100000,0.500000,19.333333,7.333333,62.333333
7,2022-09-18,12:00,Premier League,Matchweek 8,Sun,Away,W,3.0,0.0,Brentford,...,12,6,1,1.666667,1.666667,2.100000,0.900000,20.000000,6.333333,63.333333
8,2022-10-01,12:30,Premier League,Matchweek 9,Sat,Home,W,3.0,1.0,Tottenham,...,12,5,1,2.000000,1.333333,1.733333,0.800000,17.000000,6.000000,60.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,2024-02-25,13:30,Premier League,Matchweek 26,Sun,Home,W,1.0,0.0,Sheffield Utd,...,13,6,1,2.000000,1.666667,1.600000,1.733333,14.000000,6.000000,45.333333
32,2024-03-02,15:00,Premier League,Matchweek 27,Sat,Away,L,0.0,3.0,Newcastle Utd,...,15,5,0,1.000000,1.000000,1.366667,1.366667,14.000000,4.666667,54.333333
33,2024-03-09,15:00,Premier League,Matchweek 28,Sat,Home,W,2.0,1.0,Fulham,...,15,5,1,1.000000,1.333333,1.300000,1.433333,12.333333,4.000000,49.333333
35,2024-03-30,17:30,Premier League,Matchweek 30,Sat,Away,L,0.0,2.0,Aston Villa,...,17,5,0,1.000000,1.333333,0.966667,1.766667,11.000000,2.666667,55.666667
36,2024-04-02,19:45,Premier League,Matchweek 31,Tue,Away,D,1.0,1.0,Burnley,...,19,1,0,0.666667,2.000000,1.033333,1.900000,11.000000,3.000000,52.000000

In [49]:
matches_rolling.index = range(matches_rolling.shape[0])

In [50]:
matches_rolling

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,hour,day_code,target,GF_rolling,GA_rolling,xG_rolling,xGA_rolling,Sh_rolling,SoT_rolling,Poss_rolling
0,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2.0,1.0,Fulham,...,17,5,1,3.000000,0.666667,1.666667,0.666667,14.333333,5.000000,50.333333
1,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2.0,1.0,Aston Villa,...,19,2,1,3.000000,1.000000,2.200000,0.533333,18.333333,7.000000,59.333333
2,2022-09-04,16:30,Premier League,Matchweek 6,Sun,Away,L,1.0,3.0,Manchester Utd,...,16,6,0,2.333333,0.666667,2.100000,0.500000,19.333333,7.333333,62.333333
3,2022-09-18,12:00,Premier League,Matchweek 8,Sun,Away,W,3.0,0.0,Brentford,...,12,6,1,1.666667,1.666667,2.100000,0.900000,20.000000,6.333333,63.333333
4,2022-10-01,12:30,Premier League,Matchweek 9,Sat,Home,W,3.0,1.0,Tottenham,...,12,5,1,2.000000,1.333333,1.733333,0.800000,17.000000,6.000000,60.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292,2024-02-25,13:30,Premier League,Matchweek 26,Sun,Home,W,1.0,0.0,Sheffield Utd,...,13,6,1,2.000000,1.666667,1.600000,1.733333,14.000000,6.000000,45.333333
1293,2024-03-02,15:00,Premier League,Matchweek 27,Sat,Away,L,0.0,3.0,Newcastle Utd,...,15,5,0,1.000000,1.000000,1.366667,1.366667,14.000000,4.666667,54.333333
1294,2024-03-09,15:00,Premier League,Matchweek 28,Sat,Home,W,2.0,1.0,Fulham,...,15,5,1,1.000000,1.333333,1.300000,1.433333,12.333333,4.000000,49.333333
1295,2024-03-30,17:30,Premier League,Matchweek 30,Sat,Away,L,0.0,2.0,Aston Villa,...,17,5,0,1.000000,1.333333,0.966667,1.766667,11.000000,2.666667,55.666667
1296,2024-04-02,19:45,Premier League,Matchweek 31,Tue,Away,D,1.0,1.0,Burnley,...,19,1,0,0.666667,2.000000,1.033333,1.900000,11.000000,3.000000,52.000000

In [51]:
matches_rolling.shape[0]

1297

In [52]:
predictors = predictors + new_cols

In [67]:
def make_predictions(data, predictors):
    train = data[data["Date"] < '2024-01-01']
    test = data[data["Date"] > '2024-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame({"Actual" : test["target"], "Predicted" : preds}, index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, error

In [68]:
combined, precision = make_predictions(matches_rolling, predictors)

In [69]:
combined

      Actual  Predicted
55         1          0
56         1          1
57         1          1
58         1          0
59         1          1
...      ...        ...
1292       1          1
1293       0          0
1294       1          0
1295       0          0
1296       0          0

[212 rows x 2 columns]

In [70]:
test['target']

31    1
34    1
35    0
36    1
37    1
     ..
28    0
29    0
30    0
31    0
32    0
Name: target, Length: 212, dtype: int32

In [71]:
preds

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0])

In [72]:
combined = combined.merge(matches_rolling[["Date", "Team", "Opponent", "Result"]], left_index = True, right_index = True)

In [73]:
combined

,Actual,Predicted,Date,Team,Opponent,Result
55,1,0,2024-01-20,Arsenal,Crystal Palace,W
56,1,1,2024-01-30,Arsenal,Nott'ham Forest,W
57,1,1,2024-02-04,Arsenal,Liverpool,W
58,1,0,2024-02-11,Arsenal,West Ham,W
59,1,1,2024-02-17,Arsenal,Burnley,W
...,...,...,...,...,...,...
1292,1,1,2024-02-25,Wolverhampton Wanderers,Sheffield Utd,W
1293,0,0,2024-03-02,Wolverhampton Wanderers,Newcastle Utd,L
1294,1,0,2024-03-09,Wolverhampton Wanderers,Fulham,W
1295,0,0,2024-03-30,Wolverhampton Wanderers,Aston Villa,L
1296,0,0,2024-04-02,Wolverhampton Wanderers,Burnley,D

In [74]:
precision

0.5540540540540541